### ISSUE TITLE
PHP Redis 3.1.3 issue

### ISSUE THREAD

**Issue by danemacmillan** [iuscommunity-pkg/php70u-pecl-redis#2]
The latest version of Redis, `3.1.3`, has an issue. My CentOS `6.9` server was auto-updated to the version, and it broke a CI server that regularly builds Magento2 and modules for it.

There are various tickets discussing the issue:

- https://github.com/phpredis/phpredis/issues/1211
- https://github.com/magento/magento2/issues/9875

To resolve it I installed an earlier version from the `ius-archive` repo.

Remove problematic package:

-  `yum remove php70u-pecl-redis`

List package versions available from `ius-archive`:

- `yum --enablerepo ius-archive list --showduplicates php70u-pecl-redis`

Install older package:

- `yum --enablerepo ius-archive install php70u-pecl-redis-3.1.2`

If you want to prevent it from happening automatically in the future, add an exclude to the `/etc/yum.repos.d/ius.repo` file. Bear in mind that it will prevent manual updates as well:

```
[ius]
...
exclude=php70u-pecl-redis*
```

**Comment by b-harper** [comment]
Hey @danemacmillan,

It was good talking with you on IRC and thanks for creating this issue.  Does your Magento2 configuration use the credis client?  If so, did the latest version not fix this issue as noted [here][0].


[0]: https://github.com/magento/magento2/issues/9875#issuecomment-316946813

**Comment by b-harper** [comment]
Updated pecl-redis 3.1.4 packages have been released to the stable repositories.  Based on the status of the two issues you cited, this issue has been fixed.
